-- Allow batch-upserting computed engine values by id (Postgres rejects
-- explicit id values on GENERATED ALWAYS columns, which upsert needs to do).
alter table order_line_items alter column id set generated by default;
